### ISSUE TITLE
Sort a Binary Tree in Linear Time

### ISSUE THREAD

**Issue by falguni-k** [falguni-k/DS_Algo#3]
Write a C++ program to sort a Binary Tree in Linear Time.

**Comment by Harsh62Chopra** [comment]
can you please assign it to me!

**Comment by Harsh62Chopra** [comment]
@falguni-k Thanks for assigning this to me.... I've requested the compiled code to be pulled to the main branch!
Please let me know if. there's anything else that is to be done...
